services:
  - type: web
    name: etcrm-api
    env: node
    plan: free
    rootDir: server
    buildCommand: pnpm install && pnpm prisma:prod && pnpm db:prod:push
    startCommand: pnpm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
