import { LeadPhase } from "@prisma/client";
import { leadInputSchema } from "@etcrm/contracts";
import type { RequestHandler } from "express";
import { z } from "zod";
import { addSalesCallNote, claimSalesLead, createSalesLead, requestSalesClaimTransfer, updateSalesAppointment, updateSalesFollowUp, updateSalesLeadPhase, uploadSalesLeads } from "../features/sales/salesCommands.js";
import { getSalesDashboard, getSalesLead, listSalesLeads } from "../features/sales/salesQueries.js";

const phaseSchema = z.object({ phase: z.nativeEnum(LeadPhase) });
const noteSchema = z.object({ note: z.string().trim().min(2).max(5000) });
const appointmentSchema = z.object({ appointmentDate: z.string().nullable().optional() });
const followUpSchema = z.object({ nextFollowUpAt: z.string().nullable().optional() });
const transferSchema = z.object({ reason: z.string().trim().min(3).max(1000) });
const leadSchema = leadInputSchema;

export const dashboard: RequestHandler = async (req, res, next) => { try { res.json(await getSalesDashboard(req.user.id)); } catch (error) { next(error); } };
export const listMyLeads: RequestHandler = async (req, res, next) => { try { res.json(await listSalesLeads({ search: String(req.query.search || ""), phase: String(req.query.phase || ""), page: Number(req.query.page || 1), pageSize: Number(req.query.pageSize || 50) })); } catch (error) { next(error); } };
export const getLead: RequestHandler = async (req, res, next) => { try { const lead = await getSalesLead(String(req.params.id)); if (!lead) return res.status(404).json({ message: "Lead not found" }); res.json({ lead }); } catch (error) { next(error); } };
export const updateLeadPhase: RequestHandler = async (req, res, next) => { try { const phase = phaseSchema.parse(req.body).phase; if (phase === LeadPhase.CLOSED_WON) return res.status(403).json({ message: "An admin must close a lead as won and select conversion credit" }); const lead = await updateSalesLeadPhase({ leadId: String(req.params.id), userId: req.user.id, phase }); if (!lead) return res.status(404).json({ message: "Lead not found" }); res.json({ lead }); } catch (error) { next(error); } };
export const addCallNote: RequestHandler = async (req, res, next) => { try { const lead = await addSalesCallNote({ leadId: String(req.params.id), userId: req.user.id, note: noteSchema.parse(req.body).note }); if (!lead) return res.status(404).json({ message: "Lead not found" }); res.status(201).json({ lead }); } catch (error) { next(error); } };
export const updateAppointment: RequestHandler = async (req, res, next) => { try { const lead = await updateSalesAppointment({ leadId: String(req.params.id), userId: req.user.id, appointmentDate: appointmentSchema.parse(req.body).appointmentDate }); if (!lead) return res.status(404).json({ message: "Lead not found" }); res.json({ lead }); } catch (error) { next(error); } };
export const updateFollowUp: RequestHandler = async (req, res, next) => { try { const lead = await updateSalesFollowUp({ leadId: String(req.params.id), userId: req.user.id, followUpDate: followUpSchema.parse(req.body).nextFollowUpAt }); if (!lead) return res.status(404).json({ message: "Lead not found" }); res.json({ lead }); } catch (error) { next(error); } };
export const claimLead: RequestHandler = async (req, res, next) => { try { const result = await claimSalesLead({ leadId: String(req.params.id), userId: req.user.id }); if (result.status === "not-found") return res.status(404).json({ message: "Lead not found" }); if (result.status === "already-claimed") return res.status(409).json({ message: "This lead has already been claimed", claimedById: result.claimedById }); res.json({ lead: result.lead }); } catch (error) { next(error); } };
export const requestTransfer: RequestHandler = async (req, res, next) => { try { const result = await requestSalesClaimTransfer({ leadId: String(req.params.id), userId: req.user.id, reason: transferSchema.parse(req.body).reason }); if (result.status === "not-found") return res.status(404).json({ message: "Lead not found" }); if (result.status === "unclaimed" || result.status === "already-claimer") return res.status(409).json({ message: result.status === "unclaimed" ? "Claim the lead directly instead" : "You already claim this lead" }); res.status(201).json({ request: result.request }); } catch (error) { next(error); } };
export const createLead: RequestHandler = async (req, res, next) => { try { const result = await createSalesLead({ input: leadSchema.parse(req.body), userId: req.user.id }); if (result.status === "duplicate") return res.status(409).json({ message: "A lead with this phone or license already exists", duplicate: result.duplicate }); res.status(201).json({ lead: result.lead }); } catch (error) { next(error); } };
export const uploadLeads: RequestHandler = async (req, res, next) => { try { if (!req.file) return res.status(400).json({ message: "CSV or Excel file is required" }); const result = await uploadSalesLeads({ file: req.file, userId: req.user.id }); if (result.status === "empty") return res.status(400).json({ message: "No new valid leads found.", ...result }); res.status(201).json(result); } catch (error) { next(error); } };
